### ISSUE TITLE
Flying Punch sidekick crashes the game

### ISSUE THREAD

**Issue by trysdyn** [KScl/TyrianArchipelago#2]
Likely an upstream OpenTyrian thing. I figured I'd note it for now and see if I can try to replicate on vanilla OpenTyrian.

On Tyrian2000, using the newest distrib here, if you slot Flying Punch into a sidekick slot, firing it crashes the game to desktop. This can be most easily replicated with the single player OpenTyrianAP by forcing Flying Punch into starting inventory. See attached aptyrian file for ease of replication.

Works fine in the upgrade ship screen preview though. Strange.

[AP_77921782142082444814_P1_Moderately_Spiky.aptyrian.txt](https://github.com/KScl/TyrianArchipelago/files/15326957/AP_77921782142082444814_P1_Moderately_Spiky.aptyrian.txt)

**Comment by KScl** [comment]
Well, that's one way to discover a hack that was added to the engine in Tyrian 2000 that I previously didn't know about.

<details>
<summary>Technical info</summary>
Shot trail 198 apparently means "create white smoke, but only for the first segment of this shot type". Without it being handled, we were reading far beyond the end of the <a href="https://github.com/KScl/TyrianArchipelago/blob/main/src/varz.c#L774">explosion_data array</a>...
<br><br>
In OpenTyrian2000, this was relatively harmless, because the only values there are the sprite number and time-to-live. In all likelihood, the out-of-bounds reads just result in nothing being drawn. But APTyrian added an extra field to support using different sprite sheets (the new graphics for AP Items use it), and now suddenly you have a pointer to the middle of who-knows-where getting dereferenced, oops.
</details>

Fixed in 788b681.
